package jframes;

import filemanager.StudentManager;

/**
 *
 * @author Angelo
 */
public class RemoveStudent extends javax.swing.JFrame {

    /**
     * Creates new form RemoveStudent
     */
    public RemoveStudent() {
        initComponents();

        jTextArea1.append(StudentManager.showRegister());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        newStudent = new javax.swing.JButton();
        showRegister = new javax.swing.JButton();
        removeStudent = new javax.swing.JButton();
        searchByDNI1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        newStudent1 = new javax.swing.JButton();
        showRegister1 = new javax.swing.JButton();
        removeStudent1 = new javax.swing.JButton();
        searchByDNI2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        newStudent2 = new javax.swing.JButton();
        showRegister2 = new javax.swing.JButton();
        removeStudent2 = new javax.swing.JButton();
        searchByDNI3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        newStudent3 = new javax.swing.JButton();
        showRegister3 = new javax.swing.JButton();
        removeStudent3 = new javax.swing.JButton();
        searchByDNI4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        newStudent4 = new javax.swing.JButton();
        showRegister4 = new javax.swing.JButton();
        removeStudent4 = new javax.swing.JButton();
        searchByDNI5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        newStudent5 = new javax.swing.JButton();
        showRegister5 = new javax.swing.JButton();
        removeStudent5 = new javax.swing.JButton();
        searchByDNI6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        newStudent6 = new javax.swing.JButton();
        showRegister6 = new javax.swing.JButton();
        removeStudent6 = new javax.swing.JButton();
        searchByDNI7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        searchByDNI = new javax.swing.JToggleButton();
        returnMenu = new javax.swing.JToggleButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 146, 121));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestor Académico STUCOM");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newStudent.setForeground(new java.awt.Color(0, 146, 121));
        newStudent.setText("AÑADIR NUEVO ALUMNO");
        newStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentActionPerformed(evt);
            }
        });

        showRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showRegister.setForeground(new java.awt.Color(0, 146, 121));
        showRegister.setText("MOSTRAR EL REGISTRO");
        showRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRegisterActionPerformed(evt);
            }
        });

        removeStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeStudent.setForeground(new java.awt.Color(0, 146, 121));
        removeStudent.setText("ELIMINAR A UN ALUMNO");
        removeStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudentActionPerformed(evt);
            }
        });

        searchByDNI1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI1.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI1.setText("BUSCAR A UN ALUMNO");
        searchByDNI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNI1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 146, 121));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gestor Académico STUCOM");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newStudent1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newStudent1.setForeground(new java.awt.Color(0, 146, 121));
        newStudent1.setText("AÑADIR NUEVO ALUMNO");
        newStudent1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudent1ActionPerformed(evt);
            }
        });

        showRegister1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showRegister1.setForeground(new java.awt.Color(0, 146, 121));
        showRegister1.setText("MOSTRAR EL REGISTRO");
        showRegister1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRegister1ActionPerformed(evt);
            }
        });

        removeStudent1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeStudent1.setForeground(new java.awt.Color(0, 146, 121));
        removeStudent1.setText("ELIMINAR A UN ALUMNO");
        removeStudent1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudent1ActionPerformed(evt);
            }
        });

        searchByDNI2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI2.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI2.setText("BUSCAR A UN ALUMNO");
        searchByDNI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNI2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 146, 121));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gestor Académico STUCOM");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newStudent2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newStudent2.setForeground(new java.awt.Color(0, 146, 121));
        newStudent2.setText("AÑADIR NUEVO ALUMNO");
        newStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudent2ActionPerformed(evt);
            }
        });

        showRegister2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showRegister2.setForeground(new java.awt.Color(0, 146, 121));
        showRegister2.setText("MOSTRAR EL REGISTRO");
        showRegister2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRegister2ActionPerformed(evt);
            }
        });

        removeStudent2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeStudent2.setForeground(new java.awt.Color(0, 146, 121));
        removeStudent2.setText("ELIMINAR A UN ALUMNO");
        removeStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudent2ActionPerformed(evt);
            }
        });

        searchByDNI3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI3.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI3.setText("BUSCAR A UN ALUMNO");
        searchByDNI3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNI3ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 146, 121));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestor Académico STUCOM");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newStudent3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newStudent3.setForeground(new java.awt.Color(0, 146, 121));
        newStudent3.setText("AÑADIR NUEVO ALUMNO");
        newStudent3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudent3ActionPerformed(evt);
            }
        });

        showRegister3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showRegister3.setForeground(new java.awt.Color(0, 146, 121));
        showRegister3.setText("MOSTRAR EL REGISTRO");
        showRegister3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showRegister3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRegister3ActionPerformed(evt);
            }
        });

        removeStudent3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeStudent3.setForeground(new java.awt.Color(0, 146, 121));
        removeStudent3.setText("ELIMINAR A UN ALUMNO");
        removeStudent3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudent3ActionPerformed(evt);
            }
        });

        searchByDNI4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI4.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI4.setText("BUSCAR A UN ALUMNO");
        searchByDNI4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNI4ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 146, 121));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gestor Académico STUCOM");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newStudent4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newStudent4.setForeground(new java.awt.Color(0, 146, 121));
        newStudent4.setText("AÑADIR NUEVO ALUMNO");
        newStudent4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStudent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudent4ActionPerformed(evt);
            }
        });

        showRegister4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showRegister4.setForeground(new java.awt.Color(0, 146, 121));
        showRegister4.setText("MOSTRAR EL REGISTRO");
        showRegister4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showRegister4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRegister4ActionPerformed(evt);
            }
        });

        removeStudent4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeStudent4.setForeground(new java.awt.Color(0, 146, 121));
        removeStudent4.setText("ELIMINAR A UN ALUMNO");
        removeStudent4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStudent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudent4ActionPerformed(evt);
            }
        });

        searchByDNI5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI5.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI5.setText("BUSCAR A UN ALUMNO");
        searchByDNI5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNI5ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 146, 121));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gestor Académico STUCOM");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newStudent5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newStudent5.setForeground(new java.awt.Color(0, 146, 121));
        newStudent5.setText("AÑADIR NUEVO ALUMNO");
        newStudent5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStudent5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudent5ActionPerformed(evt);
            }
        });

        showRegister5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showRegister5.setForeground(new java.awt.Color(0, 146, 121));
        showRegister5.setText("MOSTRAR EL REGISTRO");
        showRegister5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showRegister5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRegister5ActionPerformed(evt);
            }
        });

        removeStudent5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeStudent5.setForeground(new java.awt.Color(0, 146, 121));
        removeStudent5.setText("ELIMINAR A UN ALUMNO");
        removeStudent5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStudent5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudent5ActionPerformed(evt);
            }
        });

        searchByDNI6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI6.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI6.setText("BUSCAR A UN ALUMNO");
        searchByDNI6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNI6ActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 146, 121));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gestor Académico STUCOM");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newStudent6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newStudent6.setForeground(new java.awt.Color(0, 146, 121));
        newStudent6.setText("AÑADIR NUEVO ALUMNO");
        newStudent6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStudent6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudent6ActionPerformed(evt);
            }
        });

        showRegister6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showRegister6.setForeground(new java.awt.Color(0, 146, 121));
        showRegister6.setText("MOSTRAR EL REGISTRO");
        showRegister6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showRegister6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRegister6ActionPerformed(evt);
            }
        });

        removeStudent6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeStudent6.setForeground(new java.awt.Color(0, 146, 121));
        removeStudent6.setText("ELIMINAR A UN ALUMNO");
        removeStudent6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStudent6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudent6ActionPerformed(evt);
            }
        });

        searchByDNI7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI7.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI7.setText("BUSCAR A UN ALUMNO");
        searchByDNI7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNI7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchByDNI7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRegister6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudent6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(newStudent6)
                .addGap(36, 36, 36)
                .addComponent(showRegister6)
                .addGap(36, 36, 36)
                .addComponent(removeStudent6)
                .addGap(36, 36, 36)
                .addComponent(searchByDNI7)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchByDNI6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRegister5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudent5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(newStudent5)
                .addGap(36, 36, 36)
                .addComponent(showRegister5)
                .addGap(36, 36, 36)
                .addComponent(removeStudent5)
                .addGap(36, 36, 36)
                .addComponent(searchByDNI6)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchByDNI5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRegister4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(newStudent4)
                .addGap(36, 36, 36)
                .addComponent(showRegister4)
                .addGap(36, 36, 36)
                .addComponent(removeStudent4)
                .addGap(36, 36, 36)
                .addComponent(searchByDNI5)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchByDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRegister3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudent3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(newStudent3)
                .addGap(36, 36, 36)
                .addComponent(showRegister3)
                .addGap(36, 36, 36)
                .addComponent(removeStudent3)
                .addGap(36, 36, 36)
                .addComponent(searchByDNI4)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchByDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(newStudent2)
                .addGap(36, 36, 36)
                .addComponent(showRegister2)
                .addGap(36, 36, 36)
                .addComponent(removeStudent2)
                .addGap(36, 36, 36)
                .addComponent(searchByDNI3)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchByDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(newStudent1)
                .addGap(36, 36, 36)
                .addComponent(showRegister1)
                .addGap(36, 36, 36)
                .addComponent(removeStudent1)
                .addGap(36, 36, 36)
                .addComponent(searchByDNI2)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchByDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(newStudent)
                .addGap(36, 36, 36)
                .addComponent(showRegister)
                .addGap(36, 36, 36)
                .addComponent(removeStudent)
                .addGap(36, 36, 36)
                .addComponent(searchByDNI1)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 343));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 146, 121));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Gestor Académico STUCOM");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Registro de todos los alumnos");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Indica el DNI del Alumno que quieres eliminar");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        searchByDNI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchByDNI.setForeground(new java.awt.Color(0, 146, 121));
        searchByDNI.setText("ELIMINAR ALUMNO");
        searchByDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchByDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDNIActionPerformed(evt);
            }
        });

        returnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnMenu.setForeground(new java.awt.Color(0, 146, 121));
        returnMenu.setText("VOLVER AL INICIO");
        returnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(searchByDNI)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(returnMenu)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(searchByDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnMenu)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void searchByDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNIActionPerformed
        StudentManager.removeStudent(jTextField1.getText());
        jTextArea1.setText("");
        jTextArea1.append(StudentManager.showRegister());
    }//GEN-LAST:event_searchByDNIActionPerformed

    private void newStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentActionPerformed
        this.setVisible(false);
        NewStudent nStudent = new NewStudent();
        nStudent.setVisible(true);
    }//GEN-LAST:event_newStudentActionPerformed

    private void showRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRegisterActionPerformed
        this.setVisible(false);
        Register register = new Register();
        register.setVisible(true);
    }//GEN-LAST:event_showRegisterActionPerformed

    private void removeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudentActionPerformed
        this.setVisible(false);
        RemoveStudent remove = new RemoveStudent();
        remove.setVisible(true);
    }//GEN-LAST:event_removeStudentActionPerformed

    private void searchByDNI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNI1ActionPerformed
        this.setVisible(false);
        SearchByDNI search = new SearchByDNI();
        search.setVisible(true);
    }//GEN-LAST:event_searchByDNI1ActionPerformed

    private void newStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudent1ActionPerformed
        this.setVisible(false);
        NewStudent nStudent = new NewStudent();
        nStudent.setVisible(true);
    }//GEN-LAST:event_newStudent1ActionPerformed

    private void showRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRegister1ActionPerformed
        this.setVisible(false);
        Register register = new Register();
        register.setVisible(true);
    }//GEN-LAST:event_showRegister1ActionPerformed

    private void removeStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudent1ActionPerformed
        this.setVisible(false);
        RemoveStudent remove = new RemoveStudent();
        remove.setVisible(true);
    }//GEN-LAST:event_removeStudent1ActionPerformed

    private void searchByDNI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNI2ActionPerformed
        this.setVisible(false);
        SearchByDNI search = new SearchByDNI();
        search.setVisible(true);
    }//GEN-LAST:event_searchByDNI2ActionPerformed

    private void newStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudent2ActionPerformed

    private void showRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRegister2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showRegister2ActionPerformed

    private void removeStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeStudent2ActionPerformed

    private void searchByDNI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNI3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByDNI3ActionPerformed

    private void newStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudent3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudent3ActionPerformed

    private void showRegister3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRegister3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showRegister3ActionPerformed

    private void removeStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudent3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeStudent3ActionPerformed

    private void searchByDNI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNI4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByDNI4ActionPerformed

    private void newStudent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudent4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudent4ActionPerformed

    private void showRegister4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRegister4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showRegister4ActionPerformed

    private void removeStudent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudent4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeStudent4ActionPerformed

    private void searchByDNI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNI5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByDNI5ActionPerformed

    private void newStudent5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudent5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudent5ActionPerformed

    private void showRegister5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRegister5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showRegister5ActionPerformed

    private void removeStudent5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudent5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeStudent5ActionPerformed

    private void searchByDNI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNI6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByDNI6ActionPerformed

    private void newStudent6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudent6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudent6ActionPerformed

    private void showRegister6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRegister6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showRegister6ActionPerformed

    private void removeStudent6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudent6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeStudent6ActionPerformed

    private void searchByDNI7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDNI7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByDNI7ActionPerformed

    private void returnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuActionPerformed
        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_returnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton newStudent;
    private javax.swing.JButton newStudent1;
    private javax.swing.JButton newStudent2;
    private javax.swing.JButton newStudent3;
    private javax.swing.JButton newStudent4;
    private javax.swing.JButton newStudent5;
    private javax.swing.JButton newStudent6;
    private javax.swing.JButton removeStudent;
    private javax.swing.JButton removeStudent1;
    private javax.swing.JButton removeStudent2;
    private javax.swing.JButton removeStudent3;
    private javax.swing.JButton removeStudent4;
    private javax.swing.JButton removeStudent5;
    private javax.swing.JButton removeStudent6;
    private javax.swing.JToggleButton returnMenu;
    private javax.swing.JToggleButton searchByDNI;
    private javax.swing.JButton searchByDNI1;
    private javax.swing.JButton searchByDNI2;
    private javax.swing.JButton searchByDNI3;
    private javax.swing.JButton searchByDNI4;
    private javax.swing.JButton searchByDNI5;
    private javax.swing.JButton searchByDNI6;
    private javax.swing.JButton searchByDNI7;
    private javax.swing.JButton showRegister;
    private javax.swing.JButton showRegister1;
    private javax.swing.JButton showRegister2;
    private javax.swing.JButton showRegister3;
    private javax.swing.JButton showRegister4;
    private javax.swing.JButton showRegister5;
    private javax.swing.JButton showRegister6;
    // End of variables declaration//GEN-END:variables
}
